#!/bin/sh

OPTIONS="-s none"
TSYNC_FILE=/home/root/cobra/tsync.conf      # $HOME is empty in a script run by systemd

if [ -f $TSYNC_FILE ] ; then
    CONF_OPTIONS=`grep frontend_options $TSYNC_FILE | sed 's/^[[:alnum:]_]*=//'`
    if [ "x$CONF_OPTIONS" != "x" ] ; then
        OPTIONS=$CONF_OPTIONS
    fi
fi

/usr/sbin/frontend $OPTIONS
